class Routes:
    BASE_EVENTS_ENDPOINT = "/api/events"
    ADD_EVENT_ENDPOINT = f"{BASE_EVENTS_ENDPOINT}/new"
    SEARCH_EVENTS_ENDPOINT = f"{BASE_EVENTS_ENDPOINT}/search"
    COUNT_EVENTS_ENDPOINT = f"{BASE_EVENTS_ENDPOINT}/count"